# Generated by Django 3.2.24 on 2026-09-02 16:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('offensive_player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=5)),
                ('defensive_player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=5)),
                ('period', models.SmallIntegerField()),
                ('seconds', models.FloatField()),
                ('fg2_made', models.IntegerField()),
                ('fg2_attempted', models.IntegerField()),
                ('fg3_made', models.IntegerField()),
                ('fg3_attempted', models.IntegerField()),
                ('fg_made', models.IntegerField()),
                ('fg_attempted', models.IntegerField()),
                ('ft_made', models.IntegerField()),
                ('ft_attempted', models.IntegerField()),
                ('rebounds_offense', models.IntegerField()),
                ('rebounds_defense', models.IntegerField()),
                ('rebound_opportunities', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('offensive_fouls', models.IntegerField()),
                ('defensive_fouls', models.IntegerField()),
                ('shooting_fouls', models.IntegerField()),
                ('points', models.IntegerField()),
                ('shot_attempts', models.IntegerField()),
                ('shot_attempt_points', models.IntegerField()),
                ('ft_potential_points', models.IntegerField()),
                ('transition_take_fouls', models.IntegerField()),
                ('defensive_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defensive_possessions', to='app.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('offensive_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offensive_possessions', to='app.team')),
            ],
            options={
                'db_table': 'possession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team')),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
